# Generated by Django 2.1.7 on 2019-08-25 15:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupwebsite', '0004_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='indeximage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='index_img', verbose_name='首页图')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
