# Generated by Django 2.1.7 on 2019-08-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='blog_img', verbose_name='首页展示')),
            ],
        ),
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ('-created_time',)},
        ),
    ]
