# Generated by Django 2.1.7 on 2019-08-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190809_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupmember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('introduction', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='peo_img', verbose_name='头像')),
            ],
            options={
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('reference', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='pub_img', verbose_name='配图')),
                ('abstract', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_time',),
            },
        ),
        migrations.DeleteModel(
            name='uploadimage',
        ),
    ]
