# Generated by Django 2.1.7 on 2019-08-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190809_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/peo_img', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/pub_img', verbose_name='配图'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
